apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 8081
  type: LoadBalancer


#  externalIPs:
#  - 192.168.1.203