apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
        - name: nfs-share
          persistentVolumeClaim:
            claimName: nfs-pvc
      imagePullSecrets:
        - name: docker-reg-cred
      containers:
        - name: php
          image: {{image}}
          imagePullPolicy: "Always"
          volumeMounts:
            - name: nfs-share
              mountPath: /var/www/
          lifecycle:
            postStart:
              exec:
                command: ['cp', '-r', '/build-code/.', '/var/www']